import { Inter } from 'next/font/google'
import Link from 'next/link'
import './globals.css'
import LoginBtn from './LoginBtn'
import LogoutBtn from './LogoutBtn'
import { getServerSession } from "next-auth"
import { authOptions } from '@/pages/api/auth/[...nextauth]'


const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {

  let session  = await getServerSession(authOptions)
  console.log(session)
  
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="navbar">
          <Link href="/">home</Link>
          <Link href="/list">list페이지</Link>
          <LoginBtn/>
          <LogoutBtn/>
        </div>
        {children}
      </body>
    </html>
  )
}
